kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: lunchbot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: lunchbot
    spec:
      containers:
      - name: lunchbot
        image: quay.io/economic/lunchbot:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        readinessProbe: &default_probe
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 7
          timeoutSeconds: 5
        livenessProbe: *default_probe
        env:
          - name: SLACK_SLASH_LUNCH
            valueFrom:
              secretKeyRef:
                name: lunchbot
                key: slackToken
      nodeSelector:
        beta.kubernetes.io/os: linux
      imagePullSecrets:
        - name: quay-ops-ro
---
kind: Service
apiVersion: v1
metadata:
  name: lunchbot
spec:
  selector:
    app: lunchbot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: lunchbot
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: lunchbot.e-conomic.ws
    http: &http_rules
      paths:
      - backend:
          serviceName: lunchbot
          servicePort: 3000
  - host: lunchbot.staging.e-conomic.ws
    http: *http_rules
  - host: lunchbot.playground.e-conomic.ws
    http: *http_rules
---
